name: Deploy

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  lambda:
    name: AWS
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Download NPM dependencies
        run: npm install

      - name: Serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
        run: node_modules/.bin/serverless deploy --stage=prod --force
